### ISSUE TITLE
Update benchmark results

### ISSUE THREAD

**Issue by alexhultman** [ITpC/LAppS#97]
Hello,

Just going to point out that a major release of uWebSockets has been out for a few months now.

It should give you a lot better results in your tests.

Would be nice if you updated the readme accordingly.

**Comment by pkpro** [comment]
Hi Alex,
You might be interested https://habr.com/ru/post/460847/

Unfortunately, I had not enough for these tests to make a comparison with uWebSockets. These large machines are gone. Please give me a sign if you'll be able to find several machines for the tests so we can compare both our tools against each another.
Regards,
Pavel.

**Comment by alexhultman** [comment]
It was more of a rhetorical thing,

I already know the answer and I can see that you have since removed any references to uWebSockets.

Problem solved, even though you still cling on to your initial conclusion even though you kind of removed the reasoning for it.

Thanks

**Comment by pkpro** [comment]
Lol, that was it? I thought you are interested in real thing. Your library is much better now since you started making it more C++ than C with classes, but still my application server beats your lib on order of magnitude. On your tests I see you can't close up to 300k erps with TLS enabled. Anyway good luck in improving your libratry.

**Comment by alexhultman** [comment]
> On your tests I see you can't close up to 300k erps with TLS enabled.

What tests are you talking about?

**Comment by alexhultman** [comment]
Sorry my dude,

I finally managed to figure out how to get LApps working on my machine (you probably want to make it easier to use).

alexhultman@clr-9c9c4beff725453db9688b589234d573~/uWebSockets.js/uWebSockets/benchmarks $ ./load_test 40 localhost 5083 0
Running benchmark now...
Msg/sec: 141515.750000
Msg/sec: 148114.500000
Msg/sec: 150802.000000
Msg/sec: 148534.750000
Msg/sec: 149844.000000
^C
alexhultman@clr-9c9c4beff725453db9688b589234d573~/uWebSockets.js/uWebSockets/benchmarks $ ./load_test 40 localhost 9001 0
Running benchmark now...
Msg/sec: 189965.750000
Msg/sec: 190446.250000
Msg/sec: 189995.000000
Msg/sec: 190335.000000
Msg/sec: 188448.000000

LApps is sweating at 200% CPU-time usage and performs significantly worse, while uWebSockets is running at 100% CPU-time and is way ahead.

There you go,

Thanks

**Comment by alexhultman** [comment]
And of course, using 200% CPU-time uWebSockets does 360k msg/sec

Questions? No?

Thanks
